src/Entity/Etalage.php
<?php

namespace App\Entity;

use App\Repository\EtalageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtalageRepository::class)]
class Etalage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $publie = null;

    #[ORM\ManyToMany(targetEntity: Livre::class, inversedBy: 'etalages', cascade: ["persist"])]
    private Collection $livres;

    #[ORM\ManyToOne(inversedBy: 'etalages')]
    private ?Amateur $amateur = null;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isPublie(): ?bool
    {
        return $this->publie;
    }

    public function setPublie(bool $publie): self
    {
        $this->publie = $publie;

        return $this;
    }

    /**
     * @return Collection<int, Livre>
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres->add($livre);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }

    public function getAmateur(): ?Amateur
    {
        return $this->amateur;
    }

    public function setAmateur(?Amateur $amateur): self
    {
        $this->amateur = $amateur;

        return $this;
    }


    public function __toString()
    {
        
        return $this-> description;

    }

}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column]
    private ?int $annee_de_parution = null;

    #[ORM\ManyToOne(inversedBy: 'livres')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Librairie $librairie = null;

    #[ORM\ManyToOne(inversedBy: 'livre')]
    private ?Genre $genre = null;

    #[ORM\ManyToMany(targetEntity: Etalage::class, mappedBy: 'livres', cascade: ["persist"])]
    private Collection $etalages;

    public function __construct()
    {
        $this->etalages = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAnneeDeParution(): ?int
    {
        return $this->annee_de_parution;
    }

    public function setAnneeDeParution(int $annee_de_parution): self
    {
        $this->annee_de_parution = $annee_de_parution;

        return $this;
    }

    public function getLibrairie(): ?Librairie
    {
        return $this->librairie;
    }

    public function setLibrairie(?Librairie $librairie): self
    {
        $this->librairie = $librairie;

        return $this;
    }

    public function __toString()
    {
        
        return $this-> titre;

    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection<int, Etalage>
     */
    public function getEtalages(): Collection
    {
        return $this->etalages;
    }

    public function addEtalage(Etalage $etalage): self
    {
        if (!$this->etalages->contains($etalage)) {
            $this->etalages->add($etalage);
            $etalage->addLivre($this);
        }

        return $this;
    }

    public function removeEtalage(Etalage $etalage): self
    {
        if ($this->etalages->removeElement($etalage)) {
            $etalage->removeLivre($this);
        }

        return $this;
    }


  
}

src/Form/EtalageType.php
<?php

namespace App\Form;

use App\Entity\Etalage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Repository\LivreRepository;

class EtalageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
                //dump($options);
                $etalage = $options['data'] ?? null;
                $amateur = $etalage->getAmateur();
        $builder
            ->add('description')
            ->add('publie')
            ->add('livres')
            ->add('amateur', null, [
                'disabled'   => true,])

                         ->add('livres', null, [
                'query_builder' => function (LivreRepository $er) use ($amateur) {
                        return $er->createQueryBuilder('g')
                        ->leftJoin('g.librairie', 'i')
                        ->andWhere('i.amateur = :amateur')
                        ->setParameter('amateur', $amateur)
                        ;
                    }
                ])  
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etalage::class,
        ]);
    }
}

src/Controller/EtalageController.php
<?php

namespace App\Controller;

use App\Entity\Amateur;
use App\Entity\Etalage;
use App\Form\EtalageType;
use App\Repository\EtalageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Livre;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use App\Entity\User;

#[Route('/etalage')]
class EtalageController extends AbstractController
{
    #[Route('/', name: 'app_etalage_index', methods: ['GET'])]
    public function index(EtalageRepository $etalageRepository): Response
    {
        $privateEtalage = array();
        $publicEtalage = array();
        $user = $this->getUser();
        if ($user) {
            $amateur = $user->getAmateur();
            $privateEtalage = $etalageRepository->findBy(
                [
                    'amateur' => $amateur,
                    'publie'  => false
                ]
            );
        }
        $publicEtalage = $etalageRepository->findBy(
            [
                'publie' => true
            ]
        );

        $etalage = array_merge($privateEtalage, $publicEtalage);

        return $this->render('etalage/index.html.twig', [
            'etalages' => $etalage
        ]);
    }

    #[Route('/new/{id}', name: 'app_etalage_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EtalageRepository $etalageRepository, Amateur $amateur): Response
    {
        $etalage = new Etalage();
        $etalage->setAmateur($amateur);
        $form = $this->createForm(EtalageType::class, $etalage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $etalageRepository->save($etalage, true);
            $this->addFlash('message', 'Création effectuée');

            return $this->redirectToRoute('app_etalage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etalage/new.html.twig', [
            'etalage' => $etalage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etalage_show', methods: ['GET'])]
    public function show(Etalage $etalage): Response

    {
        {   $amateur = $etalage->getAmateur();
            $current_amateur = $this->getUser()->getAmateur();
            if ($amateur == $current_amateur) {
                return $this->render(
                    'etalage/show.html.twig',
                    ['etalage' => $etalage]
                );
            } elseif ($this->isGranted('ROLE_ADMIN')) {
                return $this->render(
                    'etalage/show.html.twig',
                    ['etalage' => $etalage]
                );
            } else {
                return $this->render(
                    'etalage/show2.html.twig',
                    ['etalage' => $etalage]
                );
            }
        }
    }

    #[Route('/{id}/edit', name: 'app_etalage_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Etalage $etalage, EtalageRepository $etalageRepository): Response
    {
        $form = $this->createForm(EtalageType::class, $etalage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $etalageRepository->save($etalage, true);

            $this->addFlash('message', 'modification effectuée');
            return $this->redirectToRoute('app_etalage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etalage/edit.html.twig', [
            'etalage' => $etalage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etalage_delete', methods: ['POST'])]
    public function delete(Request $request, Etalage $etalage, EtalageRepository $etalageRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $etalage->getId(), $request->request->get('_token'))) {
            $etalageRepository->remove($etalage, true);
        }
        $this->addFlash('message', 'Suppression effectuée');
        return $this->redirectToRoute('app_etalage_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/{etalage_id}/livre/{livre_id}", name="app_etalage_livre_show", methods={"GET"})
     * @ParamConverter("etalage", options={"id" = "etalage_id"})
     * @ParamConverter("livre", options={"id" = "livre_id"})
     */
    public function livreShow(Etalage $etalage, Livre $livre): Response
    {
        if (!$etalage->getLivres()->contains($livre)) {
            throw $this->createNotFoundException("Ce livre ne se trouve pas dans cet étalage !");
        }
        return $this->render('etalage/livre_show.html.twig', [
            'livre' => $livre,
            'etalage' => $etalage
        ]);
    }
}

templates/etalage/_delete_form.html.twig
<form method="post" action="{{ path('app_etalage_delete', {'id': etalage.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cet étalage ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etalage.id) }}">
    <button class="btn-danger">Supprimer</button>
</form>

templates/etalage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/etalage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification de l'étalage{% endblock %}

{% block body %}
    <h1>Modification de l'étalage</h1>

    {{ include('etalage/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_etalage_index') }}">Retour</a>

    {{ include('etalage/_delete_form.html.twig') }}
{% endblock %}

templates/etalage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etalage index{% endblock %}

{% block body %}
    <h1>Etalage index</h1>
    <h4>Vous pouvez consulter les <b>étalages publiés</b> de tous les amateurs</h4>
    <p><i>NB: Vos étalages non publiés ne sont accessibles que par vous</i>

    <table class="table">
        <thead>
            <tr>
                <th>Description</th>
                <th>Amateur</th>
                <th>Publié</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etalage in etalages %}
            <tr>
                <td>{{ etalage.description }}</td>
                <td>{{ etalage.amateur }}</td>
                <td>{{ etalage.publie ? 'Oui' : 'Non' }}</td>
                <td>
                    <a href="{{ path('app_etalage_show', {'id': etalage.id}) }}">Consulter</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4"> Pas d'étalages pour le moment</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}

templates/etalage/livre_show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h1>
		{{livre.titre}}</h1>


	{% dump livre %}

	<table class="table">
		<tbody>
			<tr>
				<th>Jolibraire</th>
				<td>
					<a href="{{ path('librairie_show', {'id': livre.librairie.id}) }}">{{ livre.librairie.description}}</a>
				</td>
			</tr>
			<tr>
				<th>Titre</th>
				<td>{{ livre.titre }}</td>
			</tr>
			<tr>
				<th>
					Date
				</th>
				<td>{{ livre.anneeDeParution }}</td>
			</tr>
			<tr>
				<th>
					Genre
				</th>
				<td>
					<a href="{{ path('genre_show', {'id': livre.genre.id}) }}">{{ livre.genre.intitule }}</a>
				</td>
			</tr>
		</tbody>
	</table>

	<button class="w3-btn"><a href="javascript:history.go(-1)">Retour</a></button>


{% endblock %}

templates/etalage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel Etalage {% endblock %}

{% block body %}
    <h1>Création d'un nouvel étalage</h1>

    {{ include('etalage/_form.html.twig') }}

    <button class="w3-btn"><a href="{{ path('app_etalage_index') }}">Voir l'index des étalages</a></button>
    
{% endblock %}

templates/etalage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etalage
{% endblock %}

{% block body %}
	<h1>Etalage</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Description</th>
				<td>{{ etalage.description }}</td>
			</tr>
			<tr>
				<th>Publié</th>
				<td>{{ etalage.publie ? 'Oui' : 'Non' }}</td>
			</tr>
		</tbody>
	</table>

	<h2>Livres</h2>
	<ul>
		{% for livre in etalage.livres %}
			<li>
				<a href="{{ path('app_etalage_livre_show', {'etalage_id': etalage.id, 'livre_id' : livre.id}) }}">{{ livre }}</a>
			</li>
		{% endfor %}
	</ul>


	<button class="btn-default"><a href="{{ path('app_etalage_index') }}">Retour</a></button>

	<button class="btn-default"><a href="{{ path('app_etalage_edit', {'id': etalage.id}) }}">Modifier</a></button>

	{{ include('etalage/_delete_form.html.twig') }}
{% endblock %}

templates/etalage/show2.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etalage
{% endblock %}

{% block body %}
	<h1>Etalage</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Description</th>
				<td>{{ etalage.description }}</td>
			</tr>
			<tr>
				<th>Publié</th>
				<td>{{ etalage.publie ? 'Oui' : 'Non' }}</td>
			</tr>
		</tbody>
	</table>

	<h2>Livres</h2>
	<ul>
		{% for livre in etalage.livres %}
			<li>
				<a href="{{ path('app_etalage_livre_show', {'etalage_id': etalage.id, 'livre_id' : livre.id}) }}">{{ livre }}</a>
			</li>
		{% endfor %}
	</ul>


	<button class="btn-default"><a href="{{ path('app_etalage_index') }}">Retour</a></button>{% endblock %}